[project]
name = "epic-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "berlga-2006", email = "gar23033@byui.edu" }
]
requires-python = ">=3.9"
dependencies = []

[project.scripts]
epic-agent = "epic_agent:main"

[build-system]
requires = ["uv_build>=0.12.18,<0.13.0"]
build-backend = "uv_build"
